/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db.tables;

import java.net.URI;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import sh.xana.forum.server.db.ForumScrape;
import sh.xana.forum.server.db.Keys;
import sh.xana.forum.server.db.tables.records.PagesRecord;
import sh.xana.forum.server.dbutil.DatabaseStorage.DlStatus;
import sh.xana.forum.server.dbutil.DatabaseStorage.PageType;
import sh.xana.forum.server.dbutil.JooqGenerator.UUIDConverter;
import sh.xana.forum.server.dbutil.JooqGenerator.UriConverter;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Pages extends TableImpl<PagesRecord> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>forum-scrape.Pages</code> */
  public static final Pages PAGES = new Pages();

  /** The class holding records for this type */
  @Override
  public Class<PagesRecord> getRecordType() {
    return PagesRecord.class;
  }

  /** The column <code>forum-scrape.Pages.id</code>. */
  public final TableField<PagesRecord, UUID> ID =
      createField(
          DSL.name("id"), SQLDataType.BINARY(16).nullable(false), this, "", new UUIDConverter());

  /** The column <code>forum-scrape.Pages.sourceId</code>. */
  public final TableField<PagesRecord, UUID> SOURCEID =
      createField(
          DSL.name("sourceId"),
          SQLDataType.BINARY(16).defaultValue(DSL.field("NULL", SQLDataType.BINARY)),
          this,
          "",
          new UUIDConverter());

  /** The column <code>forum-scrape.Pages.siteid</code>. */
  public final TableField<PagesRecord, UUID> SITEID =
      createField(
          DSL.name("siteid"),
          SQLDataType.BINARY(16).nullable(false),
          this,
          "",
          new UUIDConverter());

  /** The column <code>forum-scrape.Pages.url</code>. */
  public final TableField<PagesRecord, URI> URL =
      createField(
          DSL.name("url"), SQLDataType.VARCHAR(2048).nullable(false), this, "", new UriConverter());

  /** The column <code>forum-scrape.Pages.pageType</code>. */
  public final TableField<PagesRecord, PageType> PAGETYPE =
      createField(
          DSL.name("pageType"),
          SQLDataType.VARCHAR(9).nullable(false),
          this,
          "",
          new EnumConverter<String, PageType>(String.class, PageType.class));

  /** The column <code>forum-scrape.Pages.dlstatus</code>. */
  public final TableField<PagesRecord, DlStatus> DLSTATUS =
      createField(
          DSL.name("dlstatus"),
          SQLDataType.VARCHAR(9).nullable(false),
          this,
          "",
          new EnumConverter<String, DlStatus>(String.class, DlStatus.class));

  /** The column <code>forum-scrape.Pages.updated</code>. */
  public final TableField<PagesRecord, LocalDateTime> UPDATED =
      createField(DSL.name("updated"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

  /** The column <code>forum-scrape.Pages.domain</code>. */
  public final TableField<PagesRecord, String> DOMAIN =
      createField(DSL.name("domain"), SQLDataType.VARCHAR(255).nullable(false), this, "");

  /** The column <code>forum-scrape.Pages.dlStatusCode</code>. */
  public final TableField<PagesRecord, Integer> DLSTATUSCODE =
      createField(
          DSL.name("dlStatusCode"),
          SQLDataType.INTEGER.defaultValue(DSL.field("NULL", SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>forum-scrape.Pages.exception</code>. */
  public final TableField<PagesRecord, String> EXCEPTION =
      createField(
          DSL.name("exception"),
          SQLDataType.CLOB.defaultValue(DSL.field("NULL", SQLDataType.CLOB)),
          this,
          "");

  private Pages(Name alias, Table<PagesRecord> aliased) {
    this(alias, aliased, null);
  }

  private Pages(Name alias, Table<PagesRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /** Create an aliased <code>forum-scrape.Pages</code> table reference */
  public Pages(String alias) {
    this(DSL.name(alias), PAGES);
  }

  /** Create an aliased <code>forum-scrape.Pages</code> table reference */
  public Pages(Name alias) {
    this(alias, PAGES);
  }

  /** Create a <code>forum-scrape.Pages</code> table reference */
  public Pages() {
    this(DSL.name("Pages"), null);
  }

  public <O extends Record> Pages(Table<O> child, ForeignKey<O, PagesRecord> key) {
    super(child, key, PAGES);
  }

  @Override
  public Schema getSchema() {
    return ForumScrape.FORUM_SCRAPE;
  }

  @Override
  public UniqueKey<PagesRecord> getPrimaryKey() {
    return Keys.KEY_PAGES_PRIMARY;
  }

  @Override
  public List<UniqueKey<PagesRecord>> getKeys() {
    return Arrays.<UniqueKey<PagesRecord>>asList(Keys.KEY_PAGES_PRIMARY, Keys.KEY_PAGES_URL);
  }

  @Override
  public Pages as(String alias) {
    return new Pages(DSL.name(alias), this);
  }

  @Override
  public Pages as(Name alias) {
    return new Pages(alias, this);
  }

  /** Rename this table */
  @Override
  public Pages rename(String name) {
    return new Pages(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Pages rename(Name name) {
    return new Pages(name, null);
  }

  // -------------------------------------------------------------------------
  // Row10 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row10<UUID, UUID, UUID, URI, PageType, DlStatus, LocalDateTime, String, Integer, String>
      fieldsRow() {
    return (Row10) super.fieldsRow();
  }
}
