/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.common.db;

import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import sh.xana.forum.common.db.tables.Pages;
import sh.xana.forum.common.db.tables.Sites;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultSchema extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>DEFAULT_SCHEMA</code> */
  public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

  /** The table <code>Pages</code>. */
  public final Pages PAGES = Pages.PAGES;

  /** The table <code>Sites</code>. */
  public final Sites SITES = Sites.SITES;

  /** No further instances allowed */
  private DefaultSchema() {
    super("", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.<Table<?>>asList(Pages.PAGES, Sites.SITES);
  }
}
