/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.common.db;

import sh.xana.forum.common.db.tables.Pages;
import sh.xana.forum.common.db.tables.Sites;

/** Convenience access to all tables in the default schema. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /** The table <code>Pages</code>. */
  public static final Pages PAGES = Pages.PAGES;

  /** The table <code>Sites</code>. */
  public static final Sites SITES = Sites.SITES;
}
