/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db.tables.records;

import java.net.URI;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import sh.xana.forum.server.db.tables.Pages;
import sh.xana.forum.server.dbutil.DatabaseStorage.DlStatus;
import sh.xana.forum.server.dbutil.DatabaseStorage.PageType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PagesRecord extends UpdatableRecordImpl<PagesRecord>
    implements Record10<
        UUID, UUID, UUID, URI, PageType, DlStatus, LocalDateTime, String, Integer, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>forum-scrape.Pages.id</code>. */
  public void setId(UUID value) {
    set(0, value);
  }

  /** Getter for <code>forum-scrape.Pages.id</code>. */
  public UUID getId() {
    return (UUID) get(0);
  }

  /** Setter for <code>forum-scrape.Pages.sourceId</code>. */
  public void setSourceid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>forum-scrape.Pages.sourceId</code>. */
  public UUID getSourceid() {
    return (UUID) get(1);
  }

  /** Setter for <code>forum-scrape.Pages.siteid</code>. */
  public void setSiteid(UUID value) {
    set(2, value);
  }

  /** Getter for <code>forum-scrape.Pages.siteid</code>. */
  public UUID getSiteid() {
    return (UUID) get(2);
  }

  /** Setter for <code>forum-scrape.Pages.url</code>. */
  public void setUrl(URI value) {
    set(3, value);
  }

  /** Getter for <code>forum-scrape.Pages.url</code>. */
  public URI getUrl() {
    return (URI) get(3);
  }

  /** Setter for <code>forum-scrape.Pages.pageType</code>. */
  public void setPagetype(PageType value) {
    set(4, value);
  }

  /** Getter for <code>forum-scrape.Pages.pageType</code>. */
  public PageType getPagetype() {
    return (PageType) get(4);
  }

  /** Setter for <code>forum-scrape.Pages.dlstatus</code>. */
  public void setDlstatus(DlStatus value) {
    set(5, value);
  }

  /** Getter for <code>forum-scrape.Pages.dlstatus</code>. */
  public DlStatus getDlstatus() {
    return (DlStatus) get(5);
  }

  /** Setter for <code>forum-scrape.Pages.updated</code>. */
  public void setUpdated(LocalDateTime value) {
    set(6, value);
  }

  /** Getter for <code>forum-scrape.Pages.updated</code>. */
  public LocalDateTime getUpdated() {
    return (LocalDateTime) get(6);
  }

  /** Setter for <code>forum-scrape.Pages.domain</code>. */
  public void setDomain(String value) {
    set(7, value);
  }

  /** Getter for <code>forum-scrape.Pages.domain</code>. */
  public String getDomain() {
    return (String) get(7);
  }

  /** Setter for <code>forum-scrape.Pages.dlStatusCode</code>. */
  public void setDlstatuscode(Integer value) {
    set(8, value);
  }

  /** Getter for <code>forum-scrape.Pages.dlStatusCode</code>. */
  public Integer getDlstatuscode() {
    return (Integer) get(8);
  }

  /** Setter for <code>forum-scrape.Pages.exception</code>. */
  public void setException(String value) {
    set(9, value);
  }

  /** Getter for <code>forum-scrape.Pages.exception</code>. */
  public String getException() {
    return (String) get(9);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record10 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row10<UUID, UUID, UUID, URI, PageType, DlStatus, LocalDateTime, String, Integer, String>
      fieldsRow() {
    return (Row10) super.fieldsRow();
  }

  @Override
  public Row10<UUID, UUID, UUID, URI, PageType, DlStatus, LocalDateTime, String, Integer, String>
      valuesRow() {
    return (Row10) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Pages.PAGES.ID;
  }

  @Override
  public Field<UUID> field2() {
    return Pages.PAGES.SOURCEID;
  }

  @Override
  public Field<UUID> field3() {
    return Pages.PAGES.SITEID;
  }

  @Override
  public Field<URI> field4() {
    return Pages.PAGES.URL;
  }

  @Override
  public Field<PageType> field5() {
    return Pages.PAGES.PAGETYPE;
  }

  @Override
  public Field<DlStatus> field6() {
    return Pages.PAGES.DLSTATUS;
  }

  @Override
  public Field<LocalDateTime> field7() {
    return Pages.PAGES.UPDATED;
  }

  @Override
  public Field<String> field8() {
    return Pages.PAGES.DOMAIN;
  }

  @Override
  public Field<Integer> field9() {
    return Pages.PAGES.DLSTATUSCODE;
  }

  @Override
  public Field<String> field10() {
    return Pages.PAGES.EXCEPTION;
  }

  @Override
  public UUID component1() {
    return getId();
  }

  @Override
  public UUID component2() {
    return getSourceid();
  }

  @Override
  public UUID component3() {
    return getSiteid();
  }

  @Override
  public URI component4() {
    return getUrl();
  }

  @Override
  public PageType component5() {
    return getPagetype();
  }

  @Override
  public DlStatus component6() {
    return getDlstatus();
  }

  @Override
  public LocalDateTime component7() {
    return getUpdated();
  }

  @Override
  public String component8() {
    return getDomain();
  }

  @Override
  public Integer component9() {
    return getDlstatuscode();
  }

  @Override
  public String component10() {
    return getException();
  }

  @Override
  public UUID value1() {
    return getId();
  }

  @Override
  public UUID value2() {
    return getSourceid();
  }

  @Override
  public UUID value3() {
    return getSiteid();
  }

  @Override
  public URI value4() {
    return getUrl();
  }

  @Override
  public PageType value5() {
    return getPagetype();
  }

  @Override
  public DlStatus value6() {
    return getDlstatus();
  }

  @Override
  public LocalDateTime value7() {
    return getUpdated();
  }

  @Override
  public String value8() {
    return getDomain();
  }

  @Override
  public Integer value9() {
    return getDlstatuscode();
  }

  @Override
  public String value10() {
    return getException();
  }

  @Override
  public PagesRecord value1(UUID value) {
    setId(value);
    return this;
  }

  @Override
  public PagesRecord value2(UUID value) {
    setSourceid(value);
    return this;
  }

  @Override
  public PagesRecord value3(UUID value) {
    setSiteid(value);
    return this;
  }

  @Override
  public PagesRecord value4(URI value) {
    setUrl(value);
    return this;
  }

  @Override
  public PagesRecord value5(PageType value) {
    setPagetype(value);
    return this;
  }

  @Override
  public PagesRecord value6(DlStatus value) {
    setDlstatus(value);
    return this;
  }

  @Override
  public PagesRecord value7(LocalDateTime value) {
    setUpdated(value);
    return this;
  }

  @Override
  public PagesRecord value8(String value) {
    setDomain(value);
    return this;
  }

  @Override
  public PagesRecord value9(Integer value) {
    setDlstatuscode(value);
    return this;
  }

  @Override
  public PagesRecord value10(String value) {
    setException(value);
    return this;
  }

  @Override
  public PagesRecord values(
      UUID value1,
      UUID value2,
      UUID value3,
      URI value4,
      PageType value5,
      DlStatus value6,
      LocalDateTime value7,
      String value8,
      Integer value9,
      String value10) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached PagesRecord */
  public PagesRecord() {
    super(Pages.PAGES);
  }

  /** Create a detached, initialised PagesRecord */
  public PagesRecord(
      UUID id,
      UUID sourceid,
      UUID siteid,
      URI url,
      PageType pagetype,
      DlStatus dlstatus,
      LocalDateTime updated,
      String domain,
      Integer dlstatuscode,
      String exception) {
    super(Pages.PAGES);

    setId(id);
    setSourceid(sourceid);
    setSiteid(siteid);
    setUrl(url);
    setPagetype(pagetype);
    setDlstatus(dlstatus);
    setUpdated(updated);
    setDomain(domain);
    setDlstatuscode(dlstatuscode);
    setException(exception);
  }
}
