/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db.tables.records;

import java.net.URI;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import sh.xana.forum.server.db.tables.Pages;
import sh.xana.forum.server.dbutil.DlStatus;
import sh.xana.forum.server.dbutil.PageType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PagesRecord extends UpdatableRecordImpl<PagesRecord>
    implements Record9<UUID, UUID, UUID, URI, PageType, DlStatus, LocalDateTime, Integer, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>forum-scrape.Pages.pageId</code>. */
  public void setPageid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>forum-scrape.Pages.pageId</code>. */
  public UUID getPageid() {
    return (UUID) get(0);
  }

  /** Setter for <code>forum-scrape.Pages.sourcePageId</code>. */
  public void setSourcepageid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>forum-scrape.Pages.sourcePageId</code>. */
  public UUID getSourcepageid() {
    return (UUID) get(1);
  }

  /** Setter for <code>forum-scrape.Pages.siteid</code>. */
  public void setSiteid(UUID value) {
    set(2, value);
  }

  /** Getter for <code>forum-scrape.Pages.siteid</code>. */
  public UUID getSiteid() {
    return (UUID) get(2);
  }

  /** Setter for <code>forum-scrape.Pages.pageUrl</code>. */
  public void setPageurl(URI value) {
    set(3, value);
  }

  /** Getter for <code>forum-scrape.Pages.pageUrl</code>. */
  public URI getPageurl() {
    return (URI) get(3);
  }

  /** Setter for <code>forum-scrape.Pages.pageType</code>. */
  public void setPagetype(PageType value) {
    set(4, value);
  }

  /** Getter for <code>forum-scrape.Pages.pageType</code>. */
  public PageType getPagetype() {
    return (PageType) get(4);
  }

  /** Setter for <code>forum-scrape.Pages.dlstatus</code>. */
  public void setDlstatus(DlStatus value) {
    set(5, value);
  }

  /** Getter for <code>forum-scrape.Pages.dlstatus</code>. */
  public DlStatus getDlstatus() {
    return (DlStatus) get(5);
  }

  /** Setter for <code>forum-scrape.Pages.pageUpdated</code>. */
  public void setPageupdated(LocalDateTime value) {
    set(6, value);
  }

  /** Getter for <code>forum-scrape.Pages.pageUpdated</code>. */
  public LocalDateTime getPageupdated() {
    return (LocalDateTime) get(6);
  }

  /** Setter for <code>forum-scrape.Pages.dlStatusCode</code>. */
  public void setDlstatuscode(Integer value) {
    set(7, value);
  }

  /** Getter for <code>forum-scrape.Pages.dlStatusCode</code>. */
  public Integer getDlstatuscode() {
    return (Integer) get(7);
  }

  /** Setter for <code>forum-scrape.Pages.exception</code>. */
  public void setException(String value) {
    set(8, value);
  }

  /** Getter for <code>forum-scrape.Pages.exception</code>. */
  public String getException() {
    return (String) get(8);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record9 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row9<UUID, UUID, UUID, URI, PageType, DlStatus, LocalDateTime, Integer, String>
      fieldsRow() {
    return (Row9) super.fieldsRow();
  }

  @Override
  public Row9<UUID, UUID, UUID, URI, PageType, DlStatus, LocalDateTime, Integer, String>
      valuesRow() {
    return (Row9) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Pages.PAGES.PAGEID;
  }

  @Override
  public Field<UUID> field2() {
    return Pages.PAGES.SOURCEPAGEID;
  }

  @Override
  public Field<UUID> field3() {
    return Pages.PAGES.SITEID;
  }

  @Override
  public Field<URI> field4() {
    return Pages.PAGES.PAGEURL;
  }

  @Override
  public Field<PageType> field5() {
    return Pages.PAGES.PAGETYPE;
  }

  @Override
  public Field<DlStatus> field6() {
    return Pages.PAGES.DLSTATUS;
  }

  @Override
  public Field<LocalDateTime> field7() {
    return Pages.PAGES.PAGEUPDATED;
  }

  @Override
  public Field<Integer> field8() {
    return Pages.PAGES.DLSTATUSCODE;
  }

  @Override
  public Field<String> field9() {
    return Pages.PAGES.EXCEPTION;
  }

  @Override
  public UUID component1() {
    return getPageid();
  }

  @Override
  public UUID component2() {
    return getSourcepageid();
  }

  @Override
  public UUID component3() {
    return getSiteid();
  }

  @Override
  public URI component4() {
    return getPageurl();
  }

  @Override
  public PageType component5() {
    return getPagetype();
  }

  @Override
  public DlStatus component6() {
    return getDlstatus();
  }

  @Override
  public LocalDateTime component7() {
    return getPageupdated();
  }

  @Override
  public Integer component8() {
    return getDlstatuscode();
  }

  @Override
  public String component9() {
    return getException();
  }

  @Override
  public UUID value1() {
    return getPageid();
  }

  @Override
  public UUID value2() {
    return getSourcepageid();
  }

  @Override
  public UUID value3() {
    return getSiteid();
  }

  @Override
  public URI value4() {
    return getPageurl();
  }

  @Override
  public PageType value5() {
    return getPagetype();
  }

  @Override
  public DlStatus value6() {
    return getDlstatus();
  }

  @Override
  public LocalDateTime value7() {
    return getPageupdated();
  }

  @Override
  public Integer value8() {
    return getDlstatuscode();
  }

  @Override
  public String value9() {
    return getException();
  }

  @Override
  public PagesRecord value1(UUID value) {
    setPageid(value);
    return this;
  }

  @Override
  public PagesRecord value2(UUID value) {
    setSourcepageid(value);
    return this;
  }

  @Override
  public PagesRecord value3(UUID value) {
    setSiteid(value);
    return this;
  }

  @Override
  public PagesRecord value4(URI value) {
    setPageurl(value);
    return this;
  }

  @Override
  public PagesRecord value5(PageType value) {
    setPagetype(value);
    return this;
  }

  @Override
  public PagesRecord value6(DlStatus value) {
    setDlstatus(value);
    return this;
  }

  @Override
  public PagesRecord value7(LocalDateTime value) {
    setPageupdated(value);
    return this;
  }

  @Override
  public PagesRecord value8(Integer value) {
    setDlstatuscode(value);
    return this;
  }

  @Override
  public PagesRecord value9(String value) {
    setException(value);
    return this;
  }

  @Override
  public PagesRecord values(
      UUID value1,
      UUID value2,
      UUID value3,
      URI value4,
      PageType value5,
      DlStatus value6,
      LocalDateTime value7,
      Integer value8,
      String value9) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached PagesRecord */
  public PagesRecord() {
    super(Pages.PAGES);
  }

  /** Create a detached, initialised PagesRecord */
  public PagesRecord(
      UUID pageid,
      UUID sourcepageid,
      UUID siteid,
      URI pageurl,
      PageType pagetype,
      DlStatus dlstatus,
      LocalDateTime pageupdated,
      Integer dlstatuscode,
      String exception) {
    super(Pages.PAGES);

    setPageid(pageid);
    setSourcepageid(sourcepageid);
    setSiteid(siteid);
    setPageurl(pageurl);
    setPagetype(pagetype);
    setDlstatus(dlstatus);
    setPageupdated(pageupdated);
    setDlstatuscode(dlstatuscode);
    setException(exception);
  }
}
