/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db.tables.records;

import java.net.URI;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import sh.xana.forum.server.db.tables.Sites;
import sh.xana.forum.server.dbutil.ForumType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SitesRecord extends UpdatableRecordImpl<SitesRecord>
    implements Record5<UUID, URI, LocalDateTime, ForumType, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>forum-scrape.Sites.siteId</code>. */
  public void setSiteid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>forum-scrape.Sites.siteId</code>. */
  public UUID getSiteid() {
    return (UUID) get(0);
  }

  /** Setter for <code>forum-scrape.Sites.siteUrl</code>. */
  public void setSiteurl(URI value) {
    set(1, value);
  }

  /** Getter for <code>forum-scrape.Sites.siteUrl</code>. */
  public URI getSiteurl() {
    return (URI) get(1);
  }

  /** Setter for <code>forum-scrape.Sites.siteUpdated</code>. */
  public void setSiteupdated(LocalDateTime value) {
    set(2, value);
  }

  /** Getter for <code>forum-scrape.Sites.siteUpdated</code>. */
  public LocalDateTime getSiteupdated() {
    return (LocalDateTime) get(2);
  }

  /** Setter for <code>forum-scrape.Sites.ForumType</code>. */
  public void setForumtype(ForumType value) {
    set(3, value);
  }

  /** Getter for <code>forum-scrape.Sites.ForumType</code>. */
  public ForumType getForumtype() {
    return (ForumType) get(3);
  }

  /** Setter for <code>forum-scrape.Sites.domain</code>. */
  public void setDomain(String value) {
    set(4, value);
  }

  /** Getter for <code>forum-scrape.Sites.domain</code>. */
  public String getDomain() {
    return (String) get(4);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record5 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row5<UUID, URI, LocalDateTime, ForumType, String> fieldsRow() {
    return (Row5) super.fieldsRow();
  }

  @Override
  public Row5<UUID, URI, LocalDateTime, ForumType, String> valuesRow() {
    return (Row5) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Sites.SITES.SITEID;
  }

  @Override
  public Field<URI> field2() {
    return Sites.SITES.SITEURL;
  }

  @Override
  public Field<LocalDateTime> field3() {
    return Sites.SITES.SITEUPDATED;
  }

  @Override
  public Field<ForumType> field4() {
    return Sites.SITES.FORUMTYPE;
  }

  @Override
  public Field<String> field5() {
    return Sites.SITES.DOMAIN;
  }

  @Override
  public UUID component1() {
    return getSiteid();
  }

  @Override
  public URI component2() {
    return getSiteurl();
  }

  @Override
  public LocalDateTime component3() {
    return getSiteupdated();
  }

  @Override
  public ForumType component4() {
    return getForumtype();
  }

  @Override
  public String component5() {
    return getDomain();
  }

  @Override
  public UUID value1() {
    return getSiteid();
  }

  @Override
  public URI value2() {
    return getSiteurl();
  }

  @Override
  public LocalDateTime value3() {
    return getSiteupdated();
  }

  @Override
  public ForumType value4() {
    return getForumtype();
  }

  @Override
  public String value5() {
    return getDomain();
  }

  @Override
  public SitesRecord value1(UUID value) {
    setSiteid(value);
    return this;
  }

  @Override
  public SitesRecord value2(URI value) {
    setSiteurl(value);
    return this;
  }

  @Override
  public SitesRecord value3(LocalDateTime value) {
    setSiteupdated(value);
    return this;
  }

  @Override
  public SitesRecord value4(ForumType value) {
    setForumtype(value);
    return this;
  }

  @Override
  public SitesRecord value5(String value) {
    setDomain(value);
    return this;
  }

  @Override
  public SitesRecord values(
      UUID value1, URI value2, LocalDateTime value3, ForumType value4, String value5) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached SitesRecord */
  public SitesRecord() {
    super(Sites.SITES);
  }

  /** Create a detached, initialised SitesRecord */
  public SitesRecord(
      UUID siteid, URI siteurl, LocalDateTime siteupdated, ForumType forumtype, String domain) {
    super(Sites.SITES);

    setSiteid(siteid);
    setSiteurl(siteurl);
    setSiteupdated(siteupdated);
    setForumtype(forumtype);
    setDomain(domain);
  }
}
