/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db.tables.records;

import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;
import sh.xana.forum.server.db.tables.Topics;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TopicsRecord extends TableRecordImpl<TopicsRecord>
    implements Record5<UUID, UUID, UUID, UUID, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>forum-scrape.Topics.topicId</code>. */
  public void setTopicid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>forum-scrape.Topics.topicId</code>. */
  public UUID getTopicid() {
    return (UUID) get(0);
  }

  /** Setter for <code>forum-scrape.Topics.forumId</code>. */
  public void setForumid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>forum-scrape.Topics.forumId</code>. */
  public UUID getForumid() {
    return (UUID) get(1);
  }

  /** Setter for <code>forum-scrape.Topics.firstPageId</code>. */
  public void setFirstpageid(UUID value) {
    set(2, value);
  }

  /** Getter for <code>forum-scrape.Topics.firstPageId</code>. */
  public UUID getFirstpageid() {
    return (UUID) get(2);
  }

  /** Setter for <code>forum-scrape.Topics.origId</code>. */
  public void setOrigid(UUID value) {
    set(3, value);
  }

  /** Getter for <code>forum-scrape.Topics.origId</code>. */
  public UUID getOrigid() {
    return (UUID) get(3);
  }

  /** Setter for <code>forum-scrape.Topics.name</code>. */
  public void setName(String value) {
    set(4, value);
  }

  /** Getter for <code>forum-scrape.Topics.name</code>. */
  public String getName() {
    return (String) get(4);
  }

  // -------------------------------------------------------------------------
  // Record5 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row5<UUID, UUID, UUID, UUID, String> fieldsRow() {
    return (Row5) super.fieldsRow();
  }

  @Override
  public Row5<UUID, UUID, UUID, UUID, String> valuesRow() {
    return (Row5) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Topics.TOPICS.TOPICID;
  }

  @Override
  public Field<UUID> field2() {
    return Topics.TOPICS.FORUMID;
  }

  @Override
  public Field<UUID> field3() {
    return Topics.TOPICS.FIRSTPAGEID;
  }

  @Override
  public Field<UUID> field4() {
    return Topics.TOPICS.ORIGID;
  }

  @Override
  public Field<String> field5() {
    return Topics.TOPICS.NAME;
  }

  @Override
  public UUID component1() {
    return getTopicid();
  }

  @Override
  public UUID component2() {
    return getForumid();
  }

  @Override
  public UUID component3() {
    return getFirstpageid();
  }

  @Override
  public UUID component4() {
    return getOrigid();
  }

  @Override
  public String component5() {
    return getName();
  }

  @Override
  public UUID value1() {
    return getTopicid();
  }

  @Override
  public UUID value2() {
    return getForumid();
  }

  @Override
  public UUID value3() {
    return getFirstpageid();
  }

  @Override
  public UUID value4() {
    return getOrigid();
  }

  @Override
  public String value5() {
    return getName();
  }

  @Override
  public TopicsRecord value1(UUID value) {
    setTopicid(value);
    return this;
  }

  @Override
  public TopicsRecord value2(UUID value) {
    setForumid(value);
    return this;
  }

  @Override
  public TopicsRecord value3(UUID value) {
    setFirstpageid(value);
    return this;
  }

  @Override
  public TopicsRecord value4(UUID value) {
    setOrigid(value);
    return this;
  }

  @Override
  public TopicsRecord value5(String value) {
    setName(value);
    return this;
  }

  @Override
  public TopicsRecord values(UUID value1, UUID value2, UUID value3, UUID value4, String value5) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached TopicsRecord */
  public TopicsRecord() {
    super(Topics.TOPICS);
  }

  /** Create a detached, initialised TopicsRecord */
  public TopicsRecord(UUID topicid, UUID forumid, UUID firstpageid, UUID origid, String name) {
    super(Topics.TOPICS);

    setTopicid(topicid);
    setForumid(forumid);
    setFirstpageid(firstpageid);
    setOrigid(origid);
    setName(name);
  }
}
