/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.common.db.tables.records;

import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import sh.xana.forum.common.db.tables.Pages;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PagesRecord extends UpdatableRecordImpl<PagesRecord>
    implements Record7<byte[], byte[], byte[], String, String, String, LocalDateTime> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>Pages.id</code>. */
  public void setId(byte[] value) {
    set(0, value);
  }

  /** Getter for <code>Pages.id</code>. */
  public byte[] getId() {
    return (byte[]) get(0);
  }

  /** Setter for <code>Pages.sourceId</code>. */
  public void setSourceid(byte[] value) {
    set(1, value);
  }

  /** Getter for <code>Pages.sourceId</code>. */
  public byte[] getSourceid() {
    return (byte[]) get(1);
  }

  /** Setter for <code>Pages.siteid</code>. */
  public void setSiteid(byte[] value) {
    set(2, value);
  }

  /** Getter for <code>Pages.siteid</code>. */
  public byte[] getSiteid() {
    return (byte[]) get(2);
  }

  /** Setter for <code>Pages.url</code>. */
  public void setUrl(String value) {
    set(3, value);
  }

  /** Getter for <code>Pages.url</code>. */
  public String getUrl() {
    return (String) get(3);
  }

  /** Setter for <code>Pages.pageType</code>. */
  public void setPagetype(String value) {
    set(4, value);
  }

  /** Getter for <code>Pages.pageType</code>. */
  public String getPagetype() {
    return (String) get(4);
  }

  /** Setter for <code>Pages.dlstatus</code>. */
  public void setDlstatus(String value) {
    set(5, value);
  }

  /** Getter for <code>Pages.dlstatus</code>. */
  public String getDlstatus() {
    return (String) get(5);
  }

  /** Setter for <code>Pages.updated</code>. */
  public void setUpdated(LocalDateTime value) {
    set(6, value);
  }

  /** Getter for <code>Pages.updated</code>. */
  public LocalDateTime getUpdated() {
    return (LocalDateTime) get(6);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<byte[]> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record7 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row7<byte[], byte[], byte[], String, String, String, LocalDateTime> fieldsRow() {
    return (Row7) super.fieldsRow();
  }

  @Override
  public Row7<byte[], byte[], byte[], String, String, String, LocalDateTime> valuesRow() {
    return (Row7) super.valuesRow();
  }

  @Override
  public Field<byte[]> field1() {
    return Pages.PAGES.ID;
  }

  @Override
  public Field<byte[]> field2() {
    return Pages.PAGES.SOURCEID;
  }

  @Override
  public Field<byte[]> field3() {
    return Pages.PAGES.SITEID;
  }

  @Override
  public Field<String> field4() {
    return Pages.PAGES.URL;
  }

  @Override
  public Field<String> field5() {
    return Pages.PAGES.PAGETYPE;
  }

  @Override
  public Field<String> field6() {
    return Pages.PAGES.DLSTATUS;
  }

  @Override
  public Field<LocalDateTime> field7() {
    return Pages.PAGES.UPDATED;
  }

  @Override
  public byte[] component1() {
    return getId();
  }

  @Override
  public byte[] component2() {
    return getSourceid();
  }

  @Override
  public byte[] component3() {
    return getSiteid();
  }

  @Override
  public String component4() {
    return getUrl();
  }

  @Override
  public String component5() {
    return getPagetype();
  }

  @Override
  public String component6() {
    return getDlstatus();
  }

  @Override
  public LocalDateTime component7() {
    return getUpdated();
  }

  @Override
  public byte[] value1() {
    return getId();
  }

  @Override
  public byte[] value2() {
    return getSourceid();
  }

  @Override
  public byte[] value3() {
    return getSiteid();
  }

  @Override
  public String value4() {
    return getUrl();
  }

  @Override
  public String value5() {
    return getPagetype();
  }

  @Override
  public String value6() {
    return getDlstatus();
  }

  @Override
  public LocalDateTime value7() {
    return getUpdated();
  }

  @Override
  public PagesRecord value1(byte[] value) {
    setId(value);
    return this;
  }

  @Override
  public PagesRecord value2(byte[] value) {
    setSourceid(value);
    return this;
  }

  @Override
  public PagesRecord value3(byte[] value) {
    setSiteid(value);
    return this;
  }

  @Override
  public PagesRecord value4(String value) {
    setUrl(value);
    return this;
  }

  @Override
  public PagesRecord value5(String value) {
    setPagetype(value);
    return this;
  }

  @Override
  public PagesRecord value6(String value) {
    setDlstatus(value);
    return this;
  }

  @Override
  public PagesRecord value7(LocalDateTime value) {
    setUpdated(value);
    return this;
  }

  @Override
  public PagesRecord values(
      byte[] value1,
      byte[] value2,
      byte[] value3,
      String value4,
      String value5,
      String value6,
      LocalDateTime value7) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached PagesRecord */
  public PagesRecord() {
    super(Pages.PAGES);
  }

  /** Create a detached, initialised PagesRecord */
  public PagesRecord(
      byte[] id,
      byte[] sourceid,
      byte[] siteid,
      String url,
      String pagetype,
      String dlstatus,
      LocalDateTime updated) {
    super(Pages.PAGES);

    setId(id);
    setSourceid(sourceid);
    setSiteid(siteid);
    setUrl(url);
    setPagetype(pagetype);
    setDlstatus(dlstatus);
    setUpdated(updated);
  }
}
