/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db;

import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import sh.xana.forum.server.db.tables.Dataset;
import sh.xana.forum.server.db.tables.Filedata;
import sh.xana.forum.server.db.tables.Forums;
import sh.xana.forum.server.db.tables.Pageredirects;
import sh.xana.forum.server.db.tables.Pages;
import sh.xana.forum.server.db.tables.Posts;
import sh.xana.forum.server.db.tables.Sites;
import sh.xana.forum.server.db.tables.Topics;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ForumScrape extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>forum-scrape</code> */
  public static final ForumScrape FORUM_SCRAPE = new ForumScrape();

  /** The table <code>forum-scrape.Dataset</code>. */
  public final Dataset DATASET = Dataset.DATASET;

  /** The table <code>forum-scrape.FileData</code>. */
  public final Filedata FILEDATA = Filedata.FILEDATA;

  /** The table <code>forum-scrape.Forums</code>. */
  public final Forums FORUMS = Forums.FORUMS;

  /** The table <code>forum-scrape.PageRedirects</code>. */
  public final Pageredirects PAGEREDIRECTS = Pageredirects.PAGEREDIRECTS;

  /** The table <code>forum-scrape.Pages</code>. */
  public final Pages PAGES = Pages.PAGES;

  /** The table <code>forum-scrape.Posts</code>. */
  public final Posts POSTS = Posts.POSTS;

  /** The table <code>forum-scrape.Sites</code>. */
  public final Sites SITES = Sites.SITES;

  /** The table <code>forum-scrape.Topics</code>. */
  public final Topics TOPICS = Topics.TOPICS;

  /** No further instances allowed */
  private ForumScrape() {
    super("forum-scrape", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.asList(
        Dataset.DATASET,
        Filedata.FILEDATA,
        Forums.FORUMS,
        Pageredirects.PAGEREDIRECTS,
        Pages.PAGES,
        Posts.POSTS,
        Sites.SITES,
        Topics.TOPICS);
  }
}
