/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db;

import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import sh.xana.forum.server.db.tables.Pages;
import sh.xana.forum.server.db.tables.Sites;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ForumScrape extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>forum-scrape</code> */
  public static final ForumScrape FORUM_SCRAPE = new ForumScrape();

  /** The table <code>forum-scrape.Pages</code>. */
  public final Pages PAGES = Pages.PAGES;

  /** The table <code>forum-scrape.Sites</code>. */
  public final Sites SITES = Sites.SITES;

  /** No further instances allowed */
  private ForumScrape() {
    super("forum-scrape", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.<Table<?>>asList(Pages.PAGES, Sites.SITES);
  }
}
