/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import sh.xana.forum.server.db.tables.Pageredirects;
import sh.xana.forum.server.db.tables.Pages;

/** A class modelling indexes of tables in forum-scrape. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index PAGES_DLSTATUS =
      Internal.createIndex(
          DSL.name("dlstatus"), Pages.PAGES, new OrderField[] {Pages.PAGES.DLSTATUS}, false);
  public static final Index PAGES_DLSTATUSCODE =
      Internal.createIndex(
          DSL.name("dlstatusCode"),
          Pages.PAGES,
          new OrderField[] {Pages.PAGES.DLSTATUSCODE},
          false);
  public static final Index PAGEREDIRECTS_REDIRECTURL =
      Internal.createIndex(
          DSL.name("redirectUrl"),
          Pageredirects.PAGEREDIRECTS,
          new OrderField[] {Pageredirects.PAGEREDIRECTS.REDIRECTURL},
          false);
  public static final Index PAGES_S_SITEID_STATUS =
      Internal.createIndex(
          DSL.name("S_siteId_status"),
          Pages.PAGES,
          new OrderField[] {Pages.PAGES.SITEID, Pages.PAGES.DLSTATUS},
          false);
}
