/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import sh.xana.forum.server.db.tables.Pages;
import sh.xana.forum.server.db.tables.Sites;
import sh.xana.forum.server.db.tables.records.PagesRecord;
import sh.xana.forum.server.db.tables.records.SitesRecord;

/** A class modelling foreign key relationships and constraints of tables in forum-scrape. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<PagesRecord> KEY_PAGES_PRIMARY =
      Internal.createUniqueKey(
          Pages.PAGES, DSL.name("KEY_Pages_PRIMARY"), new TableField[] {Pages.PAGES.ID}, true);
  public static final UniqueKey<PagesRecord> KEY_PAGES_URL =
      Internal.createUniqueKey(
          Pages.PAGES, DSL.name("KEY_Pages_url"), new TableField[] {Pages.PAGES.URL}, true);
  public static final UniqueKey<SitesRecord> KEY_SITES_PRIMARY =
      Internal.createUniqueKey(
          Sites.SITES, DSL.name("KEY_Sites_PRIMARY"), new TableField[] {Sites.SITES.ID}, true);
  public static final UniqueKey<SitesRecord> KEY_SITES_URL =
      Internal.createUniqueKey(
          Sites.SITES, DSL.name("KEY_Sites_url"), new TableField[] {Sites.SITES.URL}, true);
}
