/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import sh.xana.forum.server.db.tables.Pages;
import sh.xana.forum.server.db.tables.Sites;
import sh.xana.forum.server.db.tables.records.PagesRecord;
import sh.xana.forum.server.db.tables.records.SitesRecord;

/** A class modelling foreign key relationships and constraints of tables in the default schema. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<PagesRecord> PK_PAGES =
      Internal.createUniqueKey(
          Pages.PAGES, DSL.name("pk_Pages"), new TableField[] {Pages.PAGES.ID}, true);
  public static final UniqueKey<SitesRecord> PK_SITES =
      Internal.createUniqueKey(
          Sites.SITES, DSL.name("pk_Sites"), new TableField[] {Sites.SITES.ID}, true);
}
