/*
 * This file is generated by jOOQ.
 */
package sh.xana.forum.server.db;

import sh.xana.forum.server.db.tables.Filedata;
import sh.xana.forum.server.db.tables.Forums;
import sh.xana.forum.server.db.tables.Pageredirects;
import sh.xana.forum.server.db.tables.Pages;
import sh.xana.forum.server.db.tables.Posts;
import sh.xana.forum.server.db.tables.Sites;
import sh.xana.forum.server.db.tables.Topics;

/** Convenience access to all tables in forum-scrape. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /** The table <code>forum-scrape.FileData</code>. */
  public static final Filedata FILEDATA = Filedata.FILEDATA;

  /** The table <code>forum-scrape.Forums</code>. */
  public static final Forums FORUMS = Forums.FORUMS;

  /** The table <code>forum-scrape.PageRedirects</code>. */
  public static final Pageredirects PAGEREDIRECTS = Pageredirects.PAGEREDIRECTS;

  /** The table <code>forum-scrape.Pages</code>. */
  public static final Pages PAGES = Pages.PAGES;

  /** The table <code>forum-scrape.Posts</code>. */
  public static final Posts POSTS = Posts.POSTS;

  /** The table <code>forum-scrape.Sites</code>. */
  public static final Sites SITES = Sites.SITES;

  /** The table <code>forum-scrape.Topics</code>. */
  public static final Topics TOPICS = Topics.TOPICS;
}
